
-- liquibase formatted sql

-- changeset Main_user:0001

CREATE TABLE app_user(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name    VARCHAR(255) NOT NULL,
    password     VARCHAR(128) NOT NULL,
    email        VARCHAR(128),
    telegram     VARCHAR(128)

);

CREATE TABLE reminder(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255),
    description  VARCHAR(4096),
    remind       TIMESTAMP,
    user_id      BIGINT NOT NULL,
    CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);