spring:
  application:
    name: reminderApp

  datasource:
    url: jdbc:postgresql://localhost:5432/reminderdb
    username: reminder_user
    password: somepassword123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

  security:
    user:
      name: admin
      password: admin


