spring:
  application:
    name: reminderApp

  datasource:
    url: jdbc:postgresql://localhost:5432/reminderdb
    username: reminder_user
    password: somepassword123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

app:
  jwt:
    secret: "my-super-secret-key-that-is-at-least-32-characters-long"

logging:
  level:
    org.springframework.security: DEBUG